version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
    depends_on:
      - collector

  client:
    build:
      context: .
      dockerfile: Dockerfile
    command: go run client/client.go
    depends_on:
      - app

  collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    command: ["--config=/etc/otel-config.yaml"]
    ports:
      - "4317:4317" # OTLP gRPC receiver

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI port
      - "14250:14250" # Collector gRPC
    depends_on:
      - collector
